create or replace FUNCTION B_INCREM_ALL (tbl VARCHAR2)

RETURN NUMBER
AS
  C_IN NUMBER;
  C_OUT NUMBER;
BEGIN     

IF tbl = 'RESERVA' THEN
    GOTO A; 
END IF;

IF tbl = 'PRODUCTO' THEN
    GOTO B;
END IF;


<<A>>
  SELECT COUNT(1)+1 INTO C_IN FROM RESERVA;
<<B>>
  SELECT COUNT(1)+1 INTO C_IN FROM PRODUCTO;
 

  C_OUT := C_IN;

  RETURN C_OUT;

END B_INCREM_ALL;